version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db/chatdb
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: app.py
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  test:
    build: .
    command: pytest  
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db/chatdb
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
